use etl1;
select*from health_care;
desc health_care;

-- 1.RETRIVE THE NAMES OF ALL PATIENTS IN THE DATABASE
select name from health_care;

-- 2.LIST THE UNIQUE MEDICAL CONDITION PRESENT IN THE DATASET
select medical_condition from health_care group by medical_condition ;


-- 3.FIND THE TOTAL NUMBER OF DOCTORS IN THE HEALTHCARE STSTEM
select doctor from health_care group by doctor having count(doctor);

-- 4. RETRFIVE THE DETAILS OF ALL FEMALE PATIENT .
select*from health_care where gender='female';

-- 5. WHAT IS THE AVERAGE AGE OF PATIENTS IN THE DATABASE
select round(avg(age)) from health_care;

-- 6. IDENTIFY THE PATIENT WHO HAVE MORE THAN ONE MEDICAL CONDITION
SELECT  COUNT(DISTINCT medical_condition) AS num_conditions
FROM health_care
GROUP BY medical_condition
HAVING COUNT(DISTINCT medical_condition) > 1;

-- 7. LIST THE NAMES OF ALL DOCTORS
select distinct doctor from health_care;

-- 8. IDENTIFY THE MOST COMMON MEDICAL CONDITION AMONG PATIENT


-- 9. FIND THE PATIENT WHO ARE OLDER THAN 60 YEARS AND AHAVE DIABETES

-- 10. CALCULATE THE TOTAL REVENUE GENERATED BY HEALTHCARE SYSTEM
select round(sum(biling_amount)) from health_care;

-- 11. FIND THE DOCTOR WITH THE OLDEST PATIENT

-- 12 . calculate the average duration of medical visit
SELECT AVG(TIMESTAMPDIFF(day, date_of_admission, discharge_date)) AS avg_visit_duration_minutes
FROM health_care;

-- 13.GIVE THE NAMES OF PATIENT WHOSE NAME START WITH A
select name from health_care where name like 'a%';

-- 14. HOW MANY MALE AND FEMALE PATIENT ARE THERE IN DATASET
select gender,count(gender) from health_care group by gender having count(gender) ;

-- 15. how many patient are normal
select*from health_care;
select count(test_results) from health_care where test_results='normal';

-- 16 HOW MANY PATIENT ARE ABNORMAL OR INCLNCLUSIVE
select test_results, count(test_results)
 from health_care
 where test_results in ('inconclusive','abnormal')
group by test_results;
-- 17 HOW MANY PATIENT OF BLOOD GROUP AB+ ARE THERE OF AGE ABOVE 52
SELECT COUNT(*) AS patient_count
FROM health_care
WHERE blood_type = 'AB+' AND age > 52;

-- 18 HOW MANY PATIENT HAVE PAID THE BILL ABOVE 24890
select * from health_care where biling_amount>24890;

-- 19 WHAT ARE THE NAMES OF PATIENT HAVING ASTHMA
select patient_name,medical_condition 
from health_care 
where medical_condition='asthma';

-- 20 HOW MANY PATIENT HAVE CANCER
select*from health_care;
select count(*) from health_care 
where medical_condition='cancer';


-- 21 WHAT ARE THE NAMES AND BLOOD  grups of patient admitted to room no 292
select patient_name,blood_type from health_care where room_number=292;


-- 22 how many males have arthritis
select count(*) from health_care where medical_condition='arthritis';

-- 23 how many patient were admitted to harris and sons hospital
select count(*) from health_care where hospital='Harris and Sons';

-- 24 what are the names of patient whose insurance provider are cigna
select patient_name from health_care where insurance_provider='cigna';

-- 25 name the medical condition having patient whose ages is greter than average
select medical_condition from  health_care where age>(select avg(age) from health_care); 